# Generated by Django 5.2.3 on 2025-06-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Wildphotography',
            field=models.CharField(max_length=500),
        ),
    ]
